name: Tile19-instatus

on:
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.INSTATUS_API_KEY }}
  INSTATUS_PAGE_ID: ${{ secrets.INSTATUS_PAGE_ID }}
  INSTATUS_UNAVAILABLE_IMAGE_TEMPLATE_ID: ${{ secrets.INSTATUS_UNAVAILABLE_IMAGE_TEMPLATE_ID }}
  INSTATUS_AVAILABLE_IMAGE_TEMPLATE_ID: ${{ secrets.INSTATUS_AVAILABLE_IMAGE_TEMPLATE_ID }}

jobs:
  monitor-tile19-status:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        id: restore_cache
        uses: actions/cache@v4
        with:
          path: incident_id.txt
          key: incident-id-cache
          restore-keys: |
            incident-id-cache

      - name: Read cached incident ID
        run: |
          if [ -f incident_id.txt ]; then
            incident_id=$(cat incident_id.txt)
            echo "incident_id=$incident_id" >> $GITHUB_ENV
            echo "Restored incident_id from cache: '$incident_id'"
            echo "resolve_incident=true" >> $GITHUB_ENV
          else
            echo "No incident_id.txt found in cache."
          fi

      - name: Launch tile19 test
        run: |
          echo "Lancement des tests Tile19 à partir du fichier JSON..."
          test_status="OK"

          jq -c '.[]' .github/workflows/tile19-request-body.json | while read -r request_body; do
            echo "Request body: $request_body"

            response=$(curl -s -w "\n%{http_code}" -X POST "https://ifdovpj3xe.execute-api.eu-west-3.amazonaws.com/extend" \
              -H "Content-Type: application/json" \
              --data "$request_body")

            body=$(echo "$response" | sed '$d')
            http_code=$(echo "$response" | tail -n1)

            echo "Code HTTP : $http_code"
            echo "Réponse : $body"

            if [ "$http_code" -ne 200 ]; then
              echo "Request failed with body:"
              echo "$request_body"
              test_status="KO"
            fi

            echo "-------------------------------------------"
          done

          echo "test_status=$test_status" >> $GITHUB_ENV
          echo "Statut global des tests : $test_status"

      - name: Monitor tile19 availability
        id: check_tile
        run: |
          echo "Checking image availability..."
          response=$(curl -s -o response.json -w "%{http_code}" -X POST "https://ifdovpj3xe.execute-api.eu-west-3.amazonaws.com/extend" \
            -H "Content-Type: application/json" \
            --data-binary "@.github/workflows/tarn-garonne-body.json")

          echo "Status code: $response"

          if [ "$response" -ne 200 ]; then
            echo "Image retrieval failed, creating incident on Instatus..."

            instatus_response=$(curl -s -X POST "https://api.instatus.com/v1/${INSTATUS_PAGE_ID}/incidents/${INSTATUS_UNAVAILABLE_IMAGE_TEMPLATE_ID}" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $API_KEY" \
              -d '{}')

            echo "instatus_response: $instatus_response"

            incident_id=$(echo "$instatus_response" | jq -r '.id')
            echo "$incident_id" > incident_id.txt
            echo "incident_id=$incident_id" >> $GITHUB_ENV
            echo "should_cache=true" >> $GITHUB_ENV
            echo "resolve_incident=false" >> $GITHUB_ENV

          fi

      - name: Save incident_id.txt to cache
        if: ${{ env.should_cache == 'true' }}
        uses: actions/cache@v4
        with:
          path: incident_id.txt
          key: incident-id-cache

      - name: Send resolved incident to Instatus
        if: ${{ env.resolve_incident=='true' }}
        run: |
          if [ -f incident_id.txt ]; then
            incident_id=$(cat incident_id.txt)
            echo "Updating and resolve incident_id: $incident_id on Instatus..."

            curl -s -X POST "https://api.instatus.com/v2/${INSTATUS_PAGE_ID}/incidents/${incident_id}/incident-updates/${INSTATUS_AVAILABLE_IMAGE_TEMPLATE_ID}" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $API_KEY" \
              -d '{}'

            echo "Removing cached incident ID..."
            rm incident_id.txt
          else
            echo "No existing incident_id.txt found to update."
          fi